export const LANGS = { en: "en", ar: "ar" };
export const LANGS_DIRS = { en: "ltr", ar: "rtl" };
export const LANGS_FONTS = { en: "Roboto", ar: "Cairo" };
export const I18N_MAP = { en: "en", ar: "ar" };

export const SHIPMENT_STATUS = {
  TICKET_CREATED: "TICKET_CREATED",
  PACKAGE_RECEIVED: "PACKAGE_RECEIVED",
  NOT_YET_SHIPPED: "NOT_YET_SHIPPED",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  IN_TRANSIT: "IN_TRANSIT",
  WAITING_FOR_CUSTOMER_ACTION:"WAITING_FOR_CUSTOMER_ACTION",
  DELIVERED_TO_SENDER: "DELIVERED_TO_SENDER",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED"
};

export const STATUS_COLOR_MAP = {
  [SHIPMENT_STATUS.TICKET_CREATED]: "#0288d1",
  [SHIPMENT_STATUS.PACKAGE_RECEIVED]: "#ff9800",
  [SHIPMENT_STATUS.NOT_YET_SHIPPED]: "#ff9800",
  [SHIPMENT_STATUS.OUT_FOR_DELIVERY]: "#ff9800",
  [SHIPMENT_STATUS.IN_TRANSIT]: "#ff9800",
  [SHIPMENT_STATUS.WAITING_FOR_CUSTOMER_ACTION]: "#ff9800",
  [SHIPMENT_STATUS.DELIVERED_TO_SENDER]: "#ff9800",
  [SHIPMENT_STATUS.DELIVERED]: "#4caf50",
  [SHIPMENT_STATUS.CANCELLED]: "#e20714",
};